service: serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  profile: project
  region : ap-south-1
  stage : dev

resources:
  - ${file(src/serverless-resources/cognito.yml)}
